### ISSUE TITLE
Headphone connected flag

### ISSUE THREAD

**Issue by chrispike-bbc** [w3c/mediacapture-output#12]
For certain media player applications, it would be useful to know when headphones are connected (provided the operating system has this information) so that headphone-specific audio can be delivered (e.g. virtual surround). For example, Android has the ACTION_HEADSET_PLUG in the AudioManager class. Could a similar flag be made available within the medacapture-output API? It must be clear that this flag will not always be set, it would depend on the underlying system. But this would be a useful signal and one that many systems, especially mobile, do track.

Could there perhaps be a headset plugged property on each audio device and an event triggered when this status changes? Also an interface to query the current headphone plugged state on a given sinkID?

**Comment by alvestrand** [comment]
I'm not certain this makes sense - there are many ways this is wired up - for instance, USB headsets don't exist to the system until they're plugged in; some systems have physical or firmware-level switches on the headset jack that route sound to a speaker if nothing's plugged in - and the OS can't detect that; some systems (like Android quoted above) have more close software control.

For this iteration, I'd like to leave it out because it's a complexifying factor.
