### ISSUE TITLE
Reserved values for ID don't seem like the right solution

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-output#19]
After discussion on the webrtc list, it seems that the conclusion is that reserved values are a bad idea.
 (see #mediacapture-main:173)

Can we find a different solution?

**Comment by alvestrand** [comment]
https://github.com/w3c/mediacapture-main/issues/173

**Comment by vivienlacourba** [comment]
June 2015 list discussion: https://lists.w3.org/Archives/Public/public-media-capture/2015Jun/0015.html

**Comment by alvestrand** [comment]
@martinthomson and @jan-ivar were the participants on the Mediacapture-main bug. there are other ways to do this (including having a getDefaultDevice("comms") function somewhere).
Can we get more discussion here?

**Comment by alvestrand** [comment]
Would like to assign this to @guidou, but I don't seem to have the rights to do so.

**Comment by jan-ivar** [comment]
After pondering alternatives like
* `setSinkId({ category: "comms"})`,
* `setSinkId(getCategoryDeviceId("comms"))`,
* or even `setSinkId("id-comms")`

I think I've come around to wanting to see if we couldn't support just `setSinkId("comms")`. Could we limit reserved ids within the [a-z] range, and require generated device-ids to contain at least one character outside of [a-z] range?

**Comment by vivienlacourba** [comment]
@alvestrand yesterday I gave you the proper rights to assign issues on this repo. I also sent an invite to @guidou to join the editors group for this repo. Once he confirms the invite you'll be able to assign him this issue.

**Comment by guidou** [comment]
I think we should get rid of the "Predefined Device IDs" section.
As written, these special IDs are a feature specific to setSinkId.
I think this can create a number of implementation problems because the rest of the device-related specs are not aware of these special IDs. For example, from the text in the spec one can infer that these IDs should not be listed by enumerateDevices. 
From an implementation POV, this means that these IDs may need to be propagated to the places in the code where the appropriate mapping suggested by the semantics of the IDs can be performed.
I think a better solution is to allow UAs to expose abstract devices that can be used by various device-related features. For example, Chrome exposes abstract devices "default" and "communications" in enumerateDevices(). These abstract devices serve a similar purpose to the predefined IDs but can be used by setSinkId, getUserMedia or  any other function that can specify a device ID.
If we want to support more advanced semantics, we can use the getCapabilities() extension for MediaDeviceInfo, specified in https://w3c.github.io/mediacapture-main/#input-specific-device-info (and allow it not just for input devices but also output devices).
