### ISSUE TITLE
Web Audio API Extensions monkeypatch

### ISSUE THREAD

**Issue by domenic** [w3c/mediacapture-output#46]
While this is good stuff, it's not appropriate for a final spec. See https://annevankesteren.nl/2014/02/monkey-patch. It's important to track getting these changes properly upstreamed to the Web Audio specification before this spec proceeds much further.

**Comment by guidou** [comment]
@cwilso, can we move the Web Audio extensions currently in this spec to the Web Audio spec?

**Comment by dontcallmedom** [comment]
paging @padenot as an active editor of the Web Audio spec

**Comment by padenot** [comment]
Yes, I agree this is what should be done, but this is blocked by #49 and #50, which have been closed wrongly and should be addressed.

The current text is too limiting and imprecise. I cannot really be implemented and produce compatible implementations. This is not a theoretical concern, Chrome and Firefox already are incompatible on this (from manual testing).

**Comment by guidou** [comment]
The text wrt #50 is the result of a collaboration with Web Audio spec owners. Older versions of the spec proposed 4 alternative strategies, 3 of which were removed explicitly at the request of Web Audio authors in order to avoid supporting device switching.
If now there is disagreement among Web Audio authors about this, I'll be happy to remove all reference to Web Audio and let Web Audio authors solve it in the Web Audio spec.
wrt to #49, I don't think this spec is the right place to address it since it concerns how the UA should behave when the Audio Output Devices spec is not supported.
